# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'base64'

default_platform(:android)

platform :android do
    desc "Build the Android app"
    lane :build do
      gradle(task: "assembleRelease")
    end

    desc "Deploy a new version to the Google Play Store"
    lane :deploy do
      gradle(task: "clean assembleRelease")
       # Decode the Base64 encoded JSON from the environment variable
      base64_data = ENV['KEYSTORE_PASSWORD'] # The Base64 encoded string stored in an environment variable

      # Decode the Base64 string
      json_data = Base64.decode64(base64_data)

      # Write the decoded JSON data to a file
      File.open("fastlane-key.json", "w") do |file|
        file.write(json_data)
      end

      # Print the file path
      UI.message "JSON file written to: #{File.absolute_path(json_file_path)}"

       # Print the content of the fastlane-key.json file
      UI.message "Contents of fastlane-key.json:"
      UI.message File.read("fastlane-key.json")

      supply(
        json_key: "fastlane-key.json",
        track: "alpha", # or 'beta', 'alpha', 'internal', etc.
#         aab: "app/build/outputs/bundle/release/app-release.aab" # or
        apk: "app/build/outputs/apk/release/app-release-unsigned.apk"
      )
    end
end
