# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'base64'

default_platform(:android)

platform :android do
    desc "Build the Android app"
    lane :build do
      gradle(task: "assembleRelease")
    end

    desc "Deploy a new version to the Google Play Store"
    lane :deploy do
      gradle(task: "clean assembleRelease")
      supply(
        json_key_data: Base64.decode64(ENV['KEYSTORE_PASSWORD']),
        track: "alpha", # or 'beta', 'alpha', 'internal', etc.
#         aab: "app/build/outputs/bundle/release/app-release.aab" # or
        apk: "app/build/outputs/apk/release/app-release-unsigned.apk"
      )
    end
end
